feat: Implement CSharpName property on provider resource
pulumi/pulumi-terraform-bridge pull request #1551
Opened 2023-12-03 16:56 UTC by tmeckel

This PR implements the missing part for PR https://github.com/pulumi/pulumi/pull/14308 from the Pulumi SDK to have the ability to rename the generated C# (dotnet) class from it's provider resource name.

This PR comes with an update of `github.com/pulumi/pulumi/pkg/v3` and `github.com/pulumi/pulumi/sdk/v3` to at v3.95.0 because this is the first version of Pulumi which implements the required code for the `dotnet` codegen to emit a renamed class using the `CSharpName` property.

2023-12-04 07:03 UTC, iwahbe approved these changes
Hey @tmeckel.

Thanks for this PR. This looks great. I added a small change to simplify `internal/testing/schemas.go`, but otherwise I think everything is good.

2023-12-04 21:09 UTC, t0yv0 requested changes
Finishing up the p/p upgrade independently , then getting back to this.

2023-12-05 14:10 UTC, t0yv0 commented on pkg/tfbridge/info.go
> +		CSharpName: r.CSharpName,
If we are editing this, can we please edit Unmarshal() to match?

2023-12-05 14:11 UTC, t0yv0 commented on go.mod
> +	github.com/pulumi/pulumi/pkg/v3 v3.95.0
This is done now. I've rebased.

2023-12-05 14:12 UTC, t0yv0 commented
One small change requested then LGTM and can merge!

2023-12-05 14:13 UTC, t0yv0 approved these changes

2023-12-05 14:54 UTC, t0yv0 commented
Looks like it started being flaky. I'm rerunning for now, if it persists we'll investigate further.

2023-12-05 15:01 UTC, merged