Improve the documentation for adding `bridge-metadata.json`
pulumi/pulumi-terraform-bridge pull request #1691
Opened 2024-02-21 15:00 UTC by iwahbe

This is in response to https://github.com/pulumi/pulumi-terraform-bridge/issues/1690.

2024-02-21 15:01 UTC, iwahbe commented
CC @ringods

2024-02-21 15:25 UTC, ringods approved these changes

2024-02-22 18:00 UTC, guineveresaenger requested changes
There seems to be a file referenced that doesn't exist (yet)? Please disregard if GitHub is playing tricks on me.

Can we consider consolidating https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfbridge/README.md to here perhaps?

2024-02-23 16:18 UTC, iwahbe commented on docs/metadata.md
> +Provider metadata is required for PF based providers, muxed providers and [AutoAliasing](./auto-aliasing.md).
Fixed. I meant to move that section of the readme, but forgot.

2024-02-23 23:47 UTC, guineveresaenger approved these changes
LGTM!

2024-02-26 08:59 UTC, merged