Remove experimental flag for SkipDetailedDiff
pulumi/pulumi-terraform-bridge pull request #1893
Opened 2024-04-19 23:22 UTC by guineveresaenger

Removes the flag option `XSkipDetailedDiffForChanges` and rolls out behavior to all providers.

This change will break the next bridge release for pulumi-gcp and pulumi-aws. WHen updating those providers to these changes, the `XSkipDetailedDiffForChanges` provider info option must be removed.

Note that the maxItemsOne migration tests needed to be updated to show that a change of `[]` to `""` reflects a diff on the field in question now. This makes sense to me, since a nil slice is different from an empty string, but this may actually not be desired behavior, so I'd appreciate scrutiny here. Either way, the functionality under test there requires a diff to happen on MaxItemsOne migrations and that does not change.

Fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/1501.

2024-04-19 23:33 UTC, t0yv0 commented
I'm nervous as this exposes the entire AWS to new behavior over a codebase where the root cause has not been identified or fix properly tested. This change promotes a workaround from a tactical fix to the canonical behavior. Why? I'd like to request to see some evidence that the underlying problem has been fixed since the time of filing of #1501 and now; have we backfilled coverage for makeDetailedDiff or factored it properly? Have we put this code under rapid-randomized tests or newly written table driven tests that increased coverage?

2024-04-19 23:33 UTC, t0yv0 requested changes
See comment above.

2024-04-22 14:27 UTC, t0yv0 commented
Ugh, I apologize, https://github.com/pulumi/pulumi-aws/blob/upstream-v5.46.0/provider/resources.go#L5872 this is already AWS behavior somehow so there can be no possible objection on AWS grounds. I'm still ambitious for more confident testing and refactoring here but that will have to wait until we have time to do it.

2024-04-22 15:46 UTC, guineveresaenger commented
Thanks for taking a look, @t0yv0 - you are correct that this behavior has been in place for AWS for a while now. I was basing this change on [this comment](https://github.com/pulumi/pulumi-terraform-bridge/issues/1501#issuecomment-1791638511) that was primarily addressing the plan distortion.

Yes, we need to make `makeDetailedDiff` better. That's not this change. I can look into how we can test the (non-detailed) diff better than it is today.

2024-04-22 18:49 UTC, iwahbe approved these changes
Given that this change is rolled out already to our 2 largest bridged providers, I'm confident that it is well tested. 

It would be great to have more testing in the bridge, but I don't think that is necessary to merge.

2024-04-22 19:31 UTC, t0yv0 commented
We know that detailed diff is not working correctly. Not all users report issues they run into, but some do and there is a growing number of issues. If it's not working correctly the problem is more than just the current implementation is well tested. Debugging one more customer orange AWS bug that bottoms up at the detailed diff problems, I've correlated some thoughts on this  in https://github.com/pulumi/pulumi-terraform-bridge/issues/1895 - that's afaik the best way forward from what I know of today, but admittedly it still leaves set diffing behavior lacking; if we can think of a better way to do that that'd be wonderful.

2024-04-22 19:33 UTC, t0yv0 commented
IN particular when merging this I'd not consider https://github.com/pulumi/pulumi-terraform-bridge/issues/1501 adequately or sustainably fixed by this change.

2024-04-23 00:51 UTC, guineveresaenger commented
@t0yv0  - would it be alright with you to merge and follow the future work in #1895?

2024-04-23 01:35 UTC, t0yv0 commented
Totally no objections to merging - mea culpa I forgot the context that AWS already runs with this - so it's a no-op for AWS and I have no stake in the other providers anymore thanks!

2024-04-23 15:49 UTC, t0yv0 approved these changes

2024-04-23 17:15 UTC, merged